#14. Write an R program to concatenate two given factor in a single factor and display in
# descending order.
f1 <- factor(sample(LETTERS, size=7, replace=TRUE))
print(f1)
f1 <- factor(LETTERS, size=7, replace=FALSE)
print(f1)
f2 <- factor(sample(LETTERS, size=7, replace=TRUE))
print(f2)
f2 <- factor(sample(LETTERS, size=7, replace=FALSE))
print(f2)
print("Original factors:")
print(f1))
print(f2)
f = factor(c(levels(f1)[f1], levels(f2)[f2]))
print("After concatenate factor becomes:")
print(f)
print(sort(f))
print("Sort in descending order:")
print(sort(f, decreasing=TRUE))